/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  aboutSidebar: [{
    type: 'autogenerated',
    dirName: 'about',
  }],
  frontendSidebar: [{
    type: 'autogenerated',
    dirName: 'frontend',
  }],
  apiSidebar: [
    'api/index',
    {
      type: 'category',
      label: 'Docs',
      items: [
        {
          type: 'link',
          label: 'Prime API Deliverable',
          href: 'https://github.com/transcom/prime_api_deliverable',
        },
        'api/docs/push-notifications-to-prime',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/testing',
        },
      ],
    },
  ],
  devSidebar: [{
    type: 'autogenerated',
    dirName: 'dev',
  }],
  helpSidebar: [{
    type: 'autogenerated',
    dirName: 'help',
  }],
  vaultSidebar: [{
    type: 'autogenerated',
    dirName: 'vault',
  }],
  tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
