name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches: [main]
  # enables runs every day at midnight UTC
  schedule:
    - cron: "0 0 * * *"
  # enables manual runs
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # $GITHUB_WORKSPACE

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".tool-versions"
          cache: "yarn"

      - name: Install yarn
        run: npm install yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build the Docusaurus app
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: docusaurus # the branch for the deployment
          folder: build # the folder getting deployed
